// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxccsofudfajgpwmjvkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4Y2Nzb2Z1ZGZhamdwd21qdmtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwOTc2NzAsImV4cCI6MjA2NzY3MzY3MH0.b1suIXRu0ztjKoZyQeBe8U1rfICW7EqMRcSQynTRq7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});